### ISSUE TITLE
Role loading

### ISSUE THREAD

**Issue by EinsJustinn** [Global-Tags/Panel#4]
when you query a team member for the first time, the roles are not loaded

**Comment by EinsJustinn** [comment]
I think this is no longer reproducible xD

**Comment by RappyTV** [comment]
This is actually a flaw in the API and can't be really fixed that easily as I would have to make the complete permission system async which I don't want to do. Also it's just happening rn because I just restarted the API. If I didn't restart the API you probably still would've been cached.
