### ISSUE TITLE
bug: API showing old data

### ISSUE THREAD

**Issue by EinsJustinn** [Global-Tags/Panel#5]
An older player name is displayed
![image](https://github.com/user-attachments/assets/d2474ee3-40d1-48eb-97f5-e1d001affe62)

**Comment by RappyTV** [comment]
Yes I noticed that too. Imma look for an alternative API soon.

**Comment by EinsJustinn** [comment]
maybe https://laby.net/api/v3/user/{username}/uuid

**Comment by RappyTV** [comment]
> maybe https://laby.net/api/v3/user/{username}/uuid

@EinsJustinn the laby.net api also doesnt pass cors headers. i can try asking if they would enable it.
